const compliments = [
  "Your smile lights up my whole day.",
  "I love how deeply you care about people.",
  "I love how artistic you are and how beautiful your drawings are.",
  "I love your sleepy voice.",
  "I love the way you hold my hand.",
  "Your smile lights up my whole day.",
  "Your smile lights up my whole day.",
  "I love how deeply you care about people.",
  "You are way stronger than you give yourself credit for.",
  "I'm always in your corner, no matter what.",
  "Your kindness is genuine and rare.",
  "The way you find beauty in the smallest things.",
  "Your intelligence and the way your mind works.",
  "I love your resilience, you handle so much with grace.",
  "Your laugh is literally my favorite sound in the world.",
  "The way you are unapologetically yourself with me.",
  "Your sense of humor that matches mine perfectly.",
  "The way you stand up for what you believe in.",
  "I love that I can be the person you share your thoughts with.",
  "I love your busy mind, even when it gets overwhelmed.",
  "I love that you care enough to think things through so deeply.",
  "Even when you're doubting yourself, I'm 100% sure about you.",
  "I love how you communicate your feelings, even when it's hard.",
  "You are never a burden to me; I love every part of your process.",
  "I love how safe you make me feel to share my own thoughts.",
  "Your sensitivity is actually your superpower.",
  "I love that you trust me with your overthinking.",
  "The way your eyes look when you're genuinely happy.",
  "The way you style your hair.",
  "I love your fashion sense and how you express yourself.",
  "The way you look at me when you think I’m not noticing.",
  "I love your smile, it’s the highlight of my day.",
  "The way you hold my hand like you never want to let go.",
  "I love your voice, especially when you're sleepy.",
  "The way you smell like home to me.",
  "I love the little facial expressions you make without realizing it.",
  "I love how you make me want to be a better version of myself.",
  "You make the most boring days feel like an adventure.",
  "I love how I can be completely weird around you.",
  "You are my safe space after a long day.",
  "I love how you believe in me even when I don't believe in myself.",
  "You make me feel understood in a way no one else ever has.",
  "I love that I can talk to you for hours and never get bored.",
  "You make my heart race and calm my mind all at the same time.",
  "I love how you support my hobbies.",
  "You are the best part of my daily routine.",
  "I love the way we can talk about everything and nothing at all.",
  "I love the inside jokes that only we understand.",
  "I love planning our future together in my head.",
  "I love the way we've grown together since we met.",
  "I love knowing that I have you by my side for whatever comes next.",
  "I love the way you support my dreams.",
  "I love that our song always reminds me of you.",
  "I love the memories we haven't even made yet.",
  "I love that you are my best friend and my girlfriend all in one.",
  "I love that us is my favorite story.",

  "Your patience.",
  "Your soft heart.",
  "Your strength.",
  "Your curiosity.",
  "The way you say my name.",
  "Your late night texts.",
  "Your creativity.",
  "The way you listen.",
  "Your advice.",
  "Your loyalty.",
  "Your empathy.",
  "Your bravery.",
  "The way you challenge me.",
  "Your honesty.",
  "How you prioritize us.",
  "Your selflessness.",
  "The way you dream.",
  "Your focus.",
  "Your gentleness.",
  "How you handle yourself.",
  "The way you cheer me up.",
  "Your optimism, well sometimes.",
  "Your realistic side too.",
  "How you remember small details.",
  "Your little surprises.",
  "The way you hug.",
  "How you make me laugh until it hurts.",
  "Your unpredictability.",
  "Your resting face.",
  "Your excitement.",
  "How you treat others.",
  "How you treat your family.",
  "The way you light up a room.",
  "Your thinking face.",
  "Your determination, even if it’s rare.",
  "Your forgiveness.",
  "Your perspective on life.",
  "How you make me feel special.",
  "Our just because texts.",
  "The way you love me.",
  "The way you let me love you.",
  "Your existence alone.",
  "The fact that you chose me.",
  "The fact that you chose me.",

  "I love how deeply you care; it shows how big your heart is.",
  "You are never a burden to me, no matter what your mind tells you.",
  "I love that I get to be the person who calms your storm.",
  "Your thoughts are safe with me, even the messy ones.",
  "I love that you trust me enough to tell me when you’re overthinking.",
  "Even when you’re doubting yourself, I am 100% certain about you.",
  "I love your sensitivity, it’s what makes you so kind to others.",
  "I love that you think so deeply about everything; it’s part of your brilliance.",
  "You don’t have to be perfect to be the most important person in my life.",
  "I love how you communicate your feelings, even when it feels hard.",
  "I will never get tired of hearing what’s on your mind.",

  "Your voice is my favorite melody; I could listen to you talk about nothing for hours.",
  "I love it when you’re recording a voice note and you pause because you forgot what you were saying.",
  "That little hmmm you make on call when you're thinking or listening is my favorite sound.",
  "I love just hearing you breathe on the other end of the line.",
  "I love those moments where I stay silent just to listen to you.",
  "I love your overthinking because it shows how deeply you care.",
  "I love your little mood swings because they are part of the girl I love.",
  "When your mind gets too loud, I love that I get to hold you and tell you it’s okay.",
  "I love that you aren't shallow and that you have so many layers.",
  "I love how you pick yourself up even on the days when everything feels too much.",
  "I love that you’re sensitive because your heart is open and real.",

  "I love seeing you after school even when you’re tired.",
  "I love how we’re growing up together.",
  "I love that we can laugh about you slipping in your heels.",
  "I love how you make time for me even when you’re busy.",
  "I love that I think about you no matter what I’m doing.",
  "I love how our personalities just click.",
  "I love the way you treat people with kindness.",
  "I love how you inspire me to work harder.",
  "I love the messy days just as much as the perfect ones.",
  "I love that I can be silent with you and still feel happy.",
  "I love watching you evolve every single day.",

  "I love your sleepy voice, it’s soft and sweet and I could listen to it on loop.",
  "I love it when you play games with me, even when we compete.",
  "I love how our vibes match perfectly.",
  "I fell for your personality, not just your face.",
  "I love how chill you are.",
  "I love the way you handle me with love and care.",
  "I love every part of you.",
  "I love that I truly fell for who you are."
];
